name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build api-json
      run: go build 
      working-directory: src/github.com/jrolstad/golang-sandbox/api-json
    
    - name: Build multi-directory
      run: go build 
      working-directory: src/github.com/jrolstad/golang-sandbox/multi-directory

    - name: Build space-api
      run: go build 
      working-directory: src/github.com/jrolstad/golang-sandbox/space-api

    - name: Run Unit Tests
      run: go test --tags=unit
      working-directory: src/github.com/jrolstad/golang-sandbox/space-api
    
    - name: Run Integration Tests
      run: go test --tags=integration
      working-directory: src/github.com/jrolstad/golang-sandbox/space-api
